export const bettingCoreAbi = [
  // --- Functions ---
  {
    type: 'function',
    name: 'createMarket',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'marketId', type: 'bytes32' },
      { name: 'closesAt', type: 'uint256' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'placeBet',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'marketId', type: 'bytes32' },
      { name: 'outcome', type: 'uint8' },
      { name: 'amount', type: 'uint256' },
      { name: 'oddsX1000', type: 'uint256' },
      { name: 'minOddsX1000', type: 'uint256' },
    ],
    outputs: [{ name: 'betId', type: 'bytes32' }],
  },
  {
    type: 'function',
    name: 'placeBetWithAttestation',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'outcome', type: 'uint8' },
      { name: 'amount', type: 'uint256' },
      { name: 'oddsX1000', type: 'uint256' },
      { name: 'minOddsX1000', type: 'uint256' },
      {
        name: 'attestation',
        type: 'tuple',
        components: [
          { name: 'marketId', type: 'bytes32' },
          { name: 'closesAt', type: 'uint64' },
          { name: 'validUntil', type: 'uint64' },
          { name: 'signature', type: 'bytes' },
        ],
      },
    ],
    outputs: [{ name: 'betId', type: 'bytes32' }],
  },
  {
    type: 'function',
    name: 'claimWinnings',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'betId', type: 'bytes32' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'claimRefund',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'betId', type: 'bytes32' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'settleMarket',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'marketId', type: 'bytes32' },
      { name: 'winningOutcome', type: 'uint8' },
      { name: 'winningBetIds', type: 'bytes32[]' },
      { name: 'totalPayoutRequired', type: 'uint256' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'cancelMarket',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'marketId', type: 'bytes32' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'voidBet',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'betId', type: 'bytes32' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'pause',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [],
  },
  {
    type: 'function',
    name: 'unpause',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [],
  },
  {
    type: 'function',
    name: 'bets',
    stateMutability: 'view',
    inputs: [{ name: '', type: 'bytes32' }],
    outputs: [
      { name: 'bettor', type: 'address' },
      { name: 'marketId', type: 'bytes32' },
      { name: 'outcome', type: 'uint8' },
      { name: 'amount', type: 'uint256' },
      { name: 'potentialPayout', type: 'uint256' },
      { name: 'status', type: 'uint8' },
      { name: 'oddsX1000', type: 'uint256' },
      { name: 'placedAt', type: 'uint64' },
    ],
  },
  {
    type: 'function',
    name: 'markets',
    stateMutability: 'view',
    inputs: [{ name: '', type: 'bytes32' }],
    outputs: [
      { name: 'id', type: 'bytes32' },
      { name: 'status', type: 'uint8' },
      { name: 'winningOutcome', type: 'uint8' },
      { name: 'totalBetAmount', type: 'uint256' },
      { name: 'totalPayoutRequired', type: 'uint256' },
      { name: 'closesAt', type: 'uint64' },
      { name: 'fillRatioX1000', type: 'uint256' },
    ],
  },
  {
    type: 'function',
    name: 'houseEdgeBps',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'minBet',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'maxBet',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'treasury',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    type: 'function',
    name: 'usdc',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    type: 'function',
    name: 'liquidityPool',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    type: 'function',
    name: 'placeParlayBet',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'marketIds', type: 'bytes32[]' },
      { name: 'outcomes', type: 'uint8[]' },
      { name: 'stake', type: 'uint256' },
      { name: 'combinedOddsX1000', type: 'uint256' },
      { name: 'minCombinedOddsX1000', type: 'uint256' },
    ],
    outputs: [{ name: 'parlayId', type: 'bytes32' }],
  },
  {
    type: 'function',
    name: 'placeParlayBetWithAttestations',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'marketIds', type: 'bytes32[]' },
      { name: 'outcomes', type: 'uint8[]' },
      { name: 'stake', type: 'uint256' },
      { name: 'combinedOddsX1000', type: 'uint256' },
      { name: 'minCombinedOddsX1000', type: 'uint256' },
      {
        name: 'attestations',
        type: 'tuple[]',
        components: [
          { name: 'marketId', type: 'bytes32' },
          { name: 'closesAt', type: 'uint64' },
          { name: 'validUntil', type: 'uint64' },
          { name: 'signature', type: 'bytes' },
        ],
      },
    ],
    outputs: [{ name: 'parlayId', type: 'bytes32' }],
  },
  {
    type: 'function',
    name: 'claimParlayWinnings',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'parlayId', type: 'bytes32' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'claimParlayRefund',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'parlayId', type: 'bytes32' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'reportParlayLoss',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'parlayId', type: 'bytes32' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'getParlay',
    stateMutability: 'view',
    inputs: [{ name: 'parlayId', type: 'bytes32' }],
    outputs: [
      {
        name: '',
        type: 'tuple',
        components: [
          { name: 'bettor', type: 'address' },
          { name: 'marketIds', type: 'bytes32[]' },
          { name: 'outcomes', type: 'uint8[]' },
          { name: 'stake', type: 'uint256' },
          { name: 'potentialPayout', type: 'uint256' },
          { name: 'status', type: 'uint8' },
          { name: 'combinedOddsX1000', type: 'uint256' },
          { name: 'placedAt', type: 'uint64' },
        ],
      },
    ],
  },
  {
    type: 'function',
    name: 'getParlayVerdict',
    stateMutability: 'view',
    inputs: [{ name: 'parlayId', type: 'bytes32' }],
    outputs: [{ name: '', type: 'uint8' }],
  },
  // --- Events ---
  {
    type: 'event',
    name: 'MarketCreated',
    inputs: [
      { name: 'marketId', type: 'bytes32', indexed: true },
      { name: 'closesAt', type: 'uint64', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'BetPlaced',
    inputs: [
      { name: 'betId', type: 'bytes32', indexed: true },
      { name: 'marketId', type: 'bytes32', indexed: true },
      { name: 'bettor', type: 'address', indexed: true },
      { name: 'outcome', type: 'uint8', indexed: false },
      { name: 'amount', type: 'uint256', indexed: false },
      { name: 'potentialPayout', type: 'uint256', indexed: false },
      { name: 'oddsX1000', type: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'BetSettled',
    inputs: [
      { name: 'betId', type: 'bytes32', indexed: true },
      { name: 'status', type: 'uint8', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'MarketSettled',
    inputs: [
      { name: 'marketId', type: 'bytes32', indexed: true },
      { name: 'winningOutcome', type: 'uint8', indexed: false },
      { name: 'totalBetAmount', type: 'uint256', indexed: false },
      { name: 'totalPayoutRequired', type: 'uint256', indexed: false },
      { name: 'houseEdge', type: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'MarketCancelled',
    inputs: [{ name: 'marketId', type: 'bytes32', indexed: true }],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'BetVoided',
    inputs: [
      { name: 'betId', type: 'bytes32', indexed: true },
      { name: 'bettor', type: 'address', indexed: true },
      { name: 'amount', type: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'WinningsClaimed',
    inputs: [
      { name: 'betId', type: 'bytes32', indexed: true },
      { name: 'bettor', type: 'address', indexed: true },
      { name: 'amount', type: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'RefundClaimed',
    inputs: [
      { name: 'betId', type: 'bytes32', indexed: true },
      { name: 'bettor', type: 'address', indexed: true },
      { name: 'amount', type: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ParlayPlaced',
    inputs: [
      { name: 'parlayId', type: 'bytes32', indexed: true },
      { name: 'bettor', type: 'address', indexed: true },
      { name: 'marketIds', type: 'bytes32[]', indexed: false },
      { name: 'outcomes', type: 'uint8[]', indexed: false },
      { name: 'stake', type: 'uint256', indexed: false },
      { name: 'potentialPayout', type: 'uint256', indexed: false },
      { name: 'combinedOddsX1000', type: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ParlayWon',
    inputs: [
      { name: 'parlayId', type: 'bytes32', indexed: true },
      { name: 'bettor', type: 'address', indexed: true },
      { name: 'payout', type: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ParlayRefunded',
    inputs: [
      { name: 'parlayId', type: 'bytes32', indexed: true },
      { name: 'bettor', type: 'address', indexed: true },
      { name: 'amount', type: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ParlayLost',
    inputs: [
      { name: 'parlayId', type: 'bytes32', indexed: true },
      { name: 'bettor', type: 'address', indexed: true },
      { name: 'stake', type: 'uint256', indexed: false },
      { name: 'houseEdge', type: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
  // --- Errors ---
  // Confirmed present in the deployed implementation's bytecode (PUSH4/PUSH1+SHL
  // scan against the live contract, not just copied from source — see
  // LiquidityPool.ts's identical note on why that distinction matters here).
  // Listing these lets viem decode reverts by name instead of a raw selector.
  { type: 'error', name: 'MarketAlreadyExists', inputs: [] },
  { type: 'error', name: 'MarketAlreadySettled', inputs: [] },
  { type: 'error', name: 'MarketAlreadyCancelled', inputs: [] },
  { type: 'error', name: 'MarketNotOpen', inputs: [] },
  { type: 'error', name: 'InvalidOdds', inputs: [] },
  { type: 'error', name: 'BetNotFound', inputs: [] },
  { type: 'error', name: 'BetNotWon', inputs: [] },
  { type: 'error', name: 'NotBetOwner', inputs: [] },
  { type: 'error', name: 'InvalidClosesAt', inputs: [] },
  { type: 'error', name: 'PayoutSumMismatch', inputs: [] },
  { type: 'error', name: 'TooManyBets', inputs: [] },
  { type: 'error', name: 'InvalidOracleSignature', inputs: [] },
  { type: 'error', name: 'AttestationExpired', inputs: [] },
  { type: 'error', name: 'TooFewLegs', inputs: [] },
  { type: 'error', name: 'LegCountMismatch', inputs: [] },
  { type: 'error', name: 'DuplicateMarketInParlay', inputs: [] },
  { type: 'error', name: 'NotParlayOwner', inputs: [] },
  { type: 'error', name: 'ParlayAlreadyResolved', inputs: [] },
  { type: 'error', name: 'ParlayNotReady', inputs: [] },
  { type: 'error', name: 'ParlayNotWon', inputs: [] },
  { type: 'error', name: 'ParlayNotVoid', inputs: [] },
  { type: 'error', name: 'ParlayNotLost', inputs: [] },
  { type: 'error', name: 'ReentrancyGuardReentrantCall', inputs: [] },
  { type: 'error', name: 'EnforcedPause', inputs: [] },
  { type: 'error', name: 'ExpectedPause', inputs: [] },
  { type: 'error', name: 'ECDSAInvalidSignature', inputs: [] },
  {
    type: 'error',
    name: 'ECDSAInvalidSignatureLength',
    inputs: [{ name: 'length', type: 'uint256' }],
  },
  {
    type: 'error',
    name: 'ECDSAInvalidSignatureS',
    inputs: [{ name: 's', type: 'bytes32' }],
  },
  {
    type: 'error',
    name: 'SafeERC20FailedOperation',
    inputs: [{ name: 'token', type: 'address' }],
  },
] as const;
