export const bettingCoreAbi = [
  // --- Functions ---
  {
    type: 'function',
    name: 'createMarket',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'marketId', type: 'bytes32' },
      { name: 'closeTime', type: 'uint64' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'placeBet',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'marketId', type: 'bytes32' },
      { name: 'outcome', type: 'uint8' },
      { name: 'amount', type: 'uint256' },
      { name: 'oddsX1000', type: 'uint256' },
      { name: 'minOddsX1000', type: 'uint256' },
    ],
    outputs: [{ name: 'betId', type: 'bytes32' }],
  },
  {
    type: 'function',
    name: 'claimWinnings',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'betId', type: 'bytes32' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'claimRefund',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'betId', type: 'bytes32' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'settleMarket',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'marketId', type: 'bytes32' },
      { name: 'winningOutcome', type: 'uint8' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'cancelMarket',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'marketId', type: 'bytes32' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'pause',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [],
  },
  {
    type: 'function',
    name: 'unpause',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [],
  },
  {
    type: 'function',
    name: 'bets',
    stateMutability: 'view',
    inputs: [{ name: 'betId', type: 'bytes32' }],
    outputs: [
      { name: 'bettor', type: 'address' },
      { name: 'marketId', type: 'bytes32' },
      { name: 'outcome', type: 'uint8' },
      { name: 'amount', type: 'uint256' },
      { name: 'oddsX1000', type: 'uint256' },
      { name: 'payout', type: 'uint256' },
      { name: 'status', type: 'uint8' },
      { name: 'placedAt', type: 'uint64' },
    ],
  },
  {
    type: 'function',
    name: 'markets',
    stateMutability: 'view',
    inputs: [{ name: 'marketId', type: 'bytes32' }],
    outputs: [
      { name: 'pool', type: 'address' },
      { name: 'closeTime', type: 'uint64' },
      { name: 'status', type: 'uint8' },
      { name: 'winningOutcome', type: 'uint8' },
      { name: 'totalBetAmount', type: 'uint256' },
      { name: 'totalPayoutRequired', type: 'uint256' },
    ],
  },
  {
    type: 'function',
    name: 'houseEdgeBps',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'treasury',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    type: 'function',
    name: 'usdc',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    type: 'function',
    name: 'factory',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  // --- Events ---
  {
    type: 'event',
    name: 'MarketCreated',
    inputs: [
      { name: 'marketId', type: 'bytes32', indexed: true },
      { name: 'pool', type: 'address', indexed: true },
      { name: 'closeTime', type: 'uint64', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'BetPlaced',
    inputs: [
      { name: 'betId', type: 'bytes32', indexed: true },
      { name: 'marketId', type: 'bytes32', indexed: true },
      { name: 'bettor', type: 'address', indexed: true },
      { name: 'outcome', type: 'uint8', indexed: false },
      { name: 'amount', type: 'uint256', indexed: false },
      { name: 'oddsX1000', type: 'uint256', indexed: false },
      { name: 'payout', type: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'BetSettled',
    inputs: [
      { name: 'betId', type: 'bytes32', indexed: true },
      { name: 'marketId', type: 'bytes32', indexed: true },
      { name: 'status', type: 'uint8', indexed: false },
      { name: 'payout', type: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'MarketSettled',
    inputs: [
      { name: 'marketId', type: 'bytes32', indexed: true },
      { name: 'winningOutcome', type: 'uint8', indexed: false },
      { name: 'totalBetAmount', type: 'uint256', indexed: false },
      { name: 'totalPayoutRequired', type: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'MarketCancelled',
    inputs: [{ name: 'marketId', type: 'bytes32', indexed: true }],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'WinningsClaimed',
    inputs: [
      { name: 'betId', type: 'bytes32', indexed: true },
      { name: 'bettor', type: 'address', indexed: true },
      { name: 'amount', type: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'RefundClaimed',
    inputs: [
      { name: 'betId', type: 'bytes32', indexed: true },
      { name: 'bettor', type: 'address', indexed: true },
      { name: 'amount', type: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
] as const;
