// Regenerated from the compiled artifact (packages/contracts/artifacts/contracts/CrashGame.sol/CrashGame.json)
// — the previous version of this file didn't match CrashGame.sol at all
// (wrong function names/signatures, e.g. `placeBet`/`cashout`/`settleRound`
// instead of the real `joinRound`/`cashOut`/`lockRound`+`resolveRound`),
// same kind of staleness found in CasinoHouse.ts. Had zero callers before now.
export const crashGameAbi = [
  // --- Functions ---
  {
    type: 'function',
    name: 'startRound',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'serverSeedHash', type: 'bytes32' }],
    outputs: [{ name: 'roundId', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'joinRound',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'roundId', type: 'uint256' },
      { name: 'amount', type: 'uint256' },
      { name: 'autoCashoutX100', type: 'uint256' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'lockRound',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'roundId', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'cashOut',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'roundId', type: 'uint256' },
      { name: 'multiplierX100', type: 'uint256' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'resolveRound',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'roundId', type: 'uint256' },
      { name: 'serverSeed', type: 'bytes32' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'claim',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [],
  },
  {
    type: 'function',
    name: 'rounds',
    stateMutability: 'view',
    inputs: [{ name: '', type: 'uint256' }],
    outputs: [
      { name: 'id', type: 'uint256' },
      { name: 'serverSeedHash', type: 'bytes32' },
      { name: 'serverSeed', type: 'bytes32' },
      { name: 'startedAt', type: 'uint64' },
      { name: 'resolvedAt', type: 'uint64' },
      { name: 'crashMultiplierX100', type: 'uint256' },
      { name: 'totalStaked', type: 'uint256' },
      { name: 'maxPotentialPayout', type: 'uint256' },
      { name: 'status', type: 'uint8' },
      { name: 'maxSustainableCrashX100', type: 'uint256' },
    ],
  },
  {
    type: 'function',
    name: 'roundPlayers',
    stateMutability: 'view',
    inputs: [
      { name: '', type: 'uint256' },
      { name: '', type: 'uint256' },
    ],
    outputs: [
      { name: 'player', type: 'address' },
      { name: 'amount', type: 'uint256' },
      { name: 'autoCashoutX100', type: 'uint256' },
      { name: 'cashedOutAtX100', type: 'uint256' },
      { name: 'resolved', type: 'bool' },
    ],
  },
  {
    type: 'function',
    name: 'pendingPayout',
    stateMutability: 'view',
    inputs: [{ name: '', type: 'address' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'getRoundPlayerCount',
    stateMutability: 'view',
    inputs: [{ name: 'roundId', type: 'uint256' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'currentRoundId',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'MIN_STAKE',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'MAX_STAKE',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'usdc',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  // --- RTP (Phase 0: shared, admin-configurable house edge) ---
  {
    type: 'function',
    name: 'rtpBps',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'setRtp',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'newBps', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'totalPendingPayouts',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  // --- Events ---
  {
    type: 'event',
    name: 'RoundStarted',
    inputs: [
      { name: 'roundId', type: 'uint256', indexed: true },
      { name: 'serverSeedHash', type: 'bytes32', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'RoundLocked',
    inputs: [
      { name: 'roundId', type: 'uint256', indexed: true },
      { name: 'startedAt', type: 'uint64', indexed: false },
      { name: 'maxSustainableCrashX100', type: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'PlayerJoined',
    inputs: [
      { name: 'roundId', type: 'uint256', indexed: true },
      { name: 'player', type: 'address', indexed: true },
      { name: 'amount', type: 'uint256', indexed: false },
      { name: 'autoCashoutX100', type: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'PlayerCashedOut',
    inputs: [
      { name: 'roundId', type: 'uint256', indexed: true },
      { name: 'player', type: 'address', indexed: true },
      { name: 'multiplierX100', type: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'RoundResolved',
    inputs: [
      { name: 'roundId', type: 'uint256', indexed: true },
      { name: 'crashMultiplierX100', type: 'uint256', indexed: false },
      { name: 'serverSeed', type: 'bytes32', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'PayoutCredited',
    inputs: [
      { name: 'roundId', type: 'uint256', indexed: true },
      { name: 'player', type: 'address', indexed: true },
      { name: 'amount', type: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'PayoutClaimed',
    inputs: [
      { name: 'player', type: 'address', indexed: true },
      { name: 'amount', type: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'RoundCancelled',
    inputs: [
      { name: 'roundId', type: 'uint256', indexed: true },
    ],
    anonymous: false,
  },
  // --- New functions (Fix #5: escape hatch) ---
  {
    type: 'function',
    name: 'cancelStuckRound',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'roundId', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'cancelPendingRound',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'roundId', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'ROUND_TIMEOUT',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  // --- Access control views (Fix #4: governance verification) ---
  {
    type: 'function',
    name: 'DEFAULT_ADMIN_ROLE',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'bytes32' }],
  },
  {
    type: 'function',
    name: 'getRoleMember',
    stateMutability: 'view',
    inputs: [
      { name: 'role', type: 'bytes32' },
      { name: 'index', type: 'uint256' },
    ],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    type: 'function',
    name: 'hasRole',
    stateMutability: 'view',
    inputs: [
      { name: 'role', type: 'bytes32' },
      { name: 'account', type: 'address' },
    ],
    outputs: [{ name: '', type: 'bool' }],
  },
  { type: 'error', name: 'PendingRoundExists', inputs: [] },
  { type: 'error', name: 'RoundNotFound', inputs: [] },
  { type: 'error', name: 'RoundNotPending', inputs: [] },
  { type: 'error', name: 'RoundNotRunning', inputs: [] },
  { type: 'error', name: 'RoundAlreadyResolved', inputs: [] },
  { type: 'error', name: 'AlreadyJoined', inputs: [] },
  { type: 'error', name: 'NotJoined', inputs: [] },
  { type: 'error', name: 'AlreadyCashedOut', inputs: [] },
  { type: 'error', name: 'InvalidMultiplier', inputs: [] },
  { type: 'error', name: 'InvalidSeedHash', inputs: [] },
  { type: 'error', name: 'SeedMismatch', inputs: [] },
  { type: 'error', name: 'StakeOutOfRange', inputs: [] },
  { type: 'error', name: 'TooManyPlayers', inputs: [] },
  { type: 'error', name: 'InsufficientBankroll', inputs: [] },
  { type: 'error', name: 'NoPendingPayout', inputs: [] },
  { type: 'error', name: 'ZeroAmount', inputs: [] },
  { type: 'error', name: 'RoundNotTimedOut', inputs: [] },
  { type: 'error', name: 'InvalidRtp', inputs: [] },
  {
    type: 'event',
    name: 'RtpUpdated',
    inputs: [
      { name: 'oldBps', type: 'uint256', indexed: false },
      { name: 'newBps', type: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
] as const;
